name: release

on:
  push:
    tag: "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: docker:stable
    needs: [integration-test]
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Prepare docker content trust
        run: mkdir -p ~/.docker/trust/private && echo "${{ secrets.DOCKER_KEY }}" > ~/.docker/trust/private/${{ secrets.DOCKER_KEY_NAME }}
      - name: Build image
        run: docker build -t securesystemsengineering/connaisseur:$GITHUB_REF -f docker/Dockerfile .
      - name: Push image
        run: DOCKER_CONTENT_TRUST=1 docker push securesystemsengineering/connaisseur:$GITHUB_REF
